version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk-jessie
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: curl -L "$TESTS_URL" -o tests.tar
      - run: tar -xvf tests.tar -C test/Cecs475.BoardGames.Chess.Test
      - run: dotnet restore
      - run: dotnet build
      - run:
          command: |
            if [ -f GRADEME.txt ]; then
                dotnet test test/Cecs475.BoardGames.Chess.Test | tee TESTOUTPUT
                curl -X POST -H "Content-Type: text/plain" -d @TESTOUTPUT $EMAIL_URL
            fi