version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk-jessie
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: curl -L "$TESTS_URL" -o test/Cecs475.BoardGames.Chess.Test/tests.tar
      - run: tar -xvf test/Cecs475.BoardGames.Chess.Test/tests.tar
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test test/Cecs475.BoardGames.Chess.Test